### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by keplersj** [AtomFormatter/formatter#1]
1. Create provider for language where grammar isn't installed
2. ...
3. Profit! Wait... That's not right.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [formatter](https://github.com/atom-community/formatter) package, v2.12.3
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/kepler/.atom/packages/formatter/lib/main.coffee:109

TypeError: undefined is not a function
  at /Users/kepler/.atom/packages/formatter/lib/main.coffee:109:23
  at pass (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/alter/node_modules/stable/stable.js:81:21)
  at exec (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/alter/node_modules/stable/stable.js:45:9)
  at stable (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/alter/node_modules/stable/stable.js:10:12)
  at ProviderManager.providersForScopeDescriptor (/Users/kepler/.atom/packages/formatter/lib/main.coffee:108:5)
  at ProviderManager.providersForScopeDescriptor (/Users/kepler/.atom/packages/formatter/lib/main.coffee:1:1)
  at Module.formatCode (/Users/kepler/.atom/packages/formatter/lib/main.coffee:41:34)
  at atom-text-editor.<anonymous> (/Users/kepler/.atom/packages/formatter/lib/main.coffee:1:1)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:14 window:toggle-dev-tools (atom-pane.pane.active)
     -0:02.4.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:02.0 formatter:format-code (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete-ctags",
      "autocomplete-paths",
      "linter-flint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-modules, v1.0.0
color-picker, v2.0.9
file-icons, v1.5.8
formatter, v2.12.3
formatter-clang-format, v0.1.1
formatter-coffeescript, v0.1.1
formatter-uncrustify, v0.0.0
language-crystal-actual, v0.28.0
linter, v1.1.0
linter-coffeelint, v1.0.0
linter-crystal, v2.0.0
linter-jsonlint, v0.1.4
linter-ruby, v0.1.6
linter-xmllint, v0.0.7
minimap, v4.11.0
minimap-git-diff, v4.1.4
pigments, v0.8.3
react, v0.12.4
react-snippets, v0.1.4
travis-ci-status, v0.15.1

# Dev
No dev packages
```

**Comment by keplersj** [comment]
Wait. My reproduction is wrong. Something in my [uncrustify package](https://github.com/k2b6s9j/formatter-uncrustify) is causing this.

**Comment by keplersj** [comment]
I just archived the repo I opened this issue for. Closing this issue.
