### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getLastCursor' of undefined

### ISSUE THREAD

**Issue by dszpccde** [AtomFormatter/formatter#12]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: DESKTOP-6N31RQR
**Thrown From**: [formatter](https://github.com/atom-community/formatter) package 2.12.4

### Stack Trace

Uncaught TypeError: Cannot read property 'getLastCursor' of undefined

```
At C:\Users\ds\.atom\packages\formatter\lib\main.coffee:24

TypeError: Cannot read property 'getLastCursor' of undefined
    at Module.formatCode (/packages/formatter/lib/main.coffee:24:20)
    at /packages/formatter/lib/main.coffee:1:1)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
  2x -2:32 command-palette:toggle (summary.welcome-summary.icon.icon-keyboard)
  4x -0:34.6.0 core:backspace (input.hidden-input)
     -0:30.3.0 formatter:format-code (input.hidden-input)
```

### Non-Core Packages

```
formatter 2.12.4 
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-community/formatter), this package is no longer maintained and is deprecated. We recommend that people use the [Atom IDE feature](https://ide.atom.io/) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
