### ISSUE TITLE
Uncaught TypeError: _this.metadataForProvider is not a function

### ISSUE THREAD

**Issue by gouvinb** [AtomFormatter/formatter#3]
Hi,
1. dev one package formatter with [clang-format](http://clang.llvm.org/docs/ClangFormat.html) and another formatter with [js-beautify](https://github.com/beautify-web/js-beautify)
2. format a **js** file
3. I think this error is because formatting a **js** file with formatter-clangformat **and** formatter-jsbeautify despite this : 

``` coffee
{
  selector: '.source.js'
  getNewText: (text) ->
    if atom.config.get 'formatter-jsbeautify.js.enable' # I set this param at false for test
      child_process = require 'child_process'
      return new Promise (resolve, reject) ->
        ...
}
```

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [formatter](https://github.com/atom-community/formatter) package, v2.12.3
### Stack Trace

Uncaught TypeError: _this.metadataForProvider is not a function

```
At /Users/gouvin_b/.atom/packages/formatter/lib/main.coffee:109

TypeError: _this.metadataForProvider is not a function
    at /Users/gouvin_b/.atom/packages/formatter/lib/main.coffee:109:23
    at pass (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/alter/node_modules/stable/stable.js:81:21)
    at exec (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/alter/node_modules/stable/stable.js:45:9)
    at stable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/alter/node_modules/stable/stable.js:10:12)
    at ProviderManager.providersForScopeDescriptor (/Users/gouvin_b/.atom/packages/formatter/lib/main.coffee:108:5)
    at ProviderManager.providersForScopeDescriptor (/Users/gouvin_b/.atom/packages/formatter/lib/main.coffee:1:1)
    at Module.formatCode (/Users/gouvin_b/.atom/packages/formatter/lib/main.coffee:41:34)
    at atom-text-editor.<anonymous> (/Users/gouvin_b/.atom/packages/formatter/lib/main.coffee:1:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  7x -0:06.8.0 formatter:format-code (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/gouvin_b/Documents/GithubPerso/",
    "themes": [
      "one-dark-ui",
      "gl-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.1.1
formatter, v2.12.3
formatter-clangformat, v0.0.0
formatter-gofmt, v0.0.0
formatter-jsbeautify, v0.0.0
formatter-json, v0.0.0
formatter-tidy, v0.0.0
gl-light-syntax, v2.2.0
minimap, v4.19.0
pigments, v0.24.2

# Dev
No dev packages
```

**Comment by gouvinb** [comment]
I found a (bad?) fix : 

``` coffee
{CompositeDisposable} = require 'atom'

module.exports = FormatterClangformat =
  activate: (state) ->
    return

  config:
    a:
      title: 'Path to the exectuable'
      type: 'object'
      properties:
        executablePath:
          title: 'Full path of exectuable'
          type: 'string'
          default: 'clang-format'
    [...]
    js:
      title: 'Js language'
      type: 'object'
      description: 'All parameters for Js language.'
      properties:
        enable:
          title: 'Enable formatter for Js language'
          type: 'boolean'
          default: true
          description: 'Need restart Atom.'
        arguments:
          title: 'Arguments passed to the formatter Js language'
          type: 'array'
          default: []
          description: 'Example : `-assume-filename="/usr/local/mycfg/js/.clang-format"`'

  provideFormatter: ->
    [
      [...]
      {
        selector: '.source.js'
        getNewText: (text) ->
          child_process = require 'child_process'
          return new Promise (resolve, reject) ->
            [...]
      } if atom.config.get 'formatter-clangformat.js.enable'
    ]
```

But I find it dirty, because I need restart atom.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-community/formatter), this package is no longer maintained and is deprecated. We recommend that people use the [Atom IDE feature](https://ide.atom.io/) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
