### ISSUE TITLE
Uncaught TypeError: _this.metadataForProvider is not a function

### ISSUE THREAD

**Issue by hopefuture** [AtomFormatter/formatter#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [formatter](https://github.com/atom-community/formatter) package, v2.12.3
### Stack Trace

Uncaught TypeError: _this.metadataForProvider is not a function

```
At /Users/wangyanjun/.atom/packages/formatter/lib/main.coffee:109

TypeError: _this.metadataForProvider is not a function
    at /Users/wangyanjun/.atom/packages/formatter/lib/main.coffee:109:23
    at pass (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/alter/node_modules/stable/stable.js:81:21)
    at exec (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/alter/node_modules/stable/stable.js:45:9)
    at stable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/alter/node_modules/stable/stable.js:10:12)
    at ProviderManager.providersForScopeDescriptor (/Users/wangyanjun/.atom/packages/formatter/lib/main.coffee:108:5)
    at ProviderManager.providersForScopeDescriptor (/Users/wangyanjun/.atom/packages/formatter/lib/main.coffee:1:1)
    at Module.formatCode (/Users/wangyanjun/.atom/packages/formatter/lib/main.coffee:41:34)
    at atom-text-editor.<anonymous> (/Users/wangyanjun/.atom/packages/formatter/lib/main.coffee:1:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -5:55.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
  6x -4:05.5.0 formatter:format-code (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-material-ui",
      "solarized-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.19
atom-material-ui, v1.2.10
color-picker, v2.1.1
emmet, v2.4.3
formatter, v2.12.3
markdown-format, v2.5.1
markdown-table-formatter, v2.8.0
minimap, v4.21.0
open-in-browsers, v0.0.12
open-recent, v5.0.0
pigments, v0.26.0

# Dev
No dev packages
```

**Comment by gedaiu** [comment]
I get the the same error

**Comment by mrRobot62** [comment]
I'm too

any suggestions?

**Comment by nadeemja** [comment]
Me too.

**Comment by mr-nicky** [comment]
+1

**Comment by alyyasser** [comment]
+1

**Comment by jeremy-levyonline** [comment]
+1

**Comment by Chrykal** [comment]
on lines 109 and 110 change "@metadataForProvider" to "new ProviderMetadata"

https://github.com/Chrykal/formatter/commit/011e2a4a2f2c39f277967a542bd07f3eb85d23c7

**Comment by matias-casal** [comment]
+1

**Comment by richardhosler** [comment]
109  --  specificityA = @metadataForProvider(providerA).getSpecificity(scopeChain)
110  --  specificityB = @metadataForProvider(providerB).getSpecificity(scopeChain)
109  ++  specificityA = new ProviderMetadata(providerA).getSpecificity(scopeChain)
110  ++  specificityB = new ProviderMetadata(providerB).getSpecificity(scopeChain)

did have a pull request for this issue but project seems to be abandoned...

**Comment by tedyuen** [comment]
+1

**Comment by Kinzi** [comment]
+1

**Comment by martinoTc** [comment]
+1

**Comment by lucafilosofi** [comment]
Hi all,

Actually i had to install CoffeeScript and TypeScript in order to make the package to work.

`npm install -g coffeescript`

`npm install -g typescript`

reload atom

**Comment by TinyCalf** [comment]
solved my problem! Thx

**Comment by chrisnicholls** [comment]
I installed those two packages with npm but then I also had to install the [atom-typescript](https://atom.io/packages/atom-typescript) package in atom to get it to work

**Comment by hesapadim** [comment]
Installed coffescript, typescript, and atom-typescript package, still getting same error.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-community/formatter), this package is no longer maintained and is deprecated. We recommend that people use the [Atom IDE feature](https://ide.atom.io/) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
